#!/usr/bin/env python
import sys

from astrodendro.viewer.viewer import DendroViewer

if len(sys.argv) == 2:
    filename = sys.argv[1]
    v = DendroViewer(filename)
    v.run()
else:
	exit("Pass a FITS filename as an argument to launch the viewer.")